%% Shortcut to this section

clear, clc, close all

load melcomp_3_fullWorkspace.mat %load everything generated by the code above
load melcomp_3_correlation_results.mat %load the results of the above code run (until corr_return) for all signals

%%
clc

for i=1:size(cs,3)
    c_t(:,:,i) = corr(cs(1:5,:,i)');
end

c = mean(c_t,3);

figure, imagesc(c)
colormap('gray')
colorbar

%% Plot the different signals against eachother and look at correlation (FOR ILLUMINANT #1)

ill = 500;

md = max(max(cs(1:5,:,ill))); %max data

%figure, scatter(cs(1,range,1),cs(2,range,1))

figure('Color','white')
for j=1:5
    for i = 1:5
        if i==j
            continue
        end
        subplot(5,5,i+(j-1)*5)
        scatter(cs(j,:,ill),cs(i,:,ill),'k.') %only plotting points for 1 illuminant
        xlabel(plt_lbls(j))
        ylabel(plt_lbls(i))
        
        
        xlim([0 md])
        ylim([0 md])
        xticklabels([])
        yticklabels([])        
        set(gca,'Color',repmat(c(i,j),3,1))
        
        text(md/10,md-md/10,num2str(c(i,j),2))
    end
end

%%




